package datapipe.core.data.generator

/**
 * @author: andrei shlykov
 * @since: 21.01.2018
 */
class AutoGeneratedClassLoader: ClassLoader() {

    fun loadNewClass(className: String, byteCode: ByteArray) =
            defineClass(className, byteCode, 0, byteCode.size)

}